---
- name: Install nginx server
  hosts: server
  become: yes
  tasks:
    - name: install nginx
      dnf:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
  tasks:
    - name: install python
      dnf:
        name: python
        state: present
    -name: start python
      ansible.builtin.service:
        name: python
        state: started
        enabled: yes    