- name: play level variables
  hosts: local
  connection: local # ansible is cnnecting to localhost
  vars:
    COURSE: ansible
    Duration: 10hrs
    Trainer: venkat
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "course name is: {{ COURSE }},  Duration: {{ Duration }}, trainer: {{ Trainer }}"